/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nimbusds.jose.aws.kms.crypto;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
