version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - . ./gradle_install.sh
  build:
    commands:
      - echo "Build started on `date`"
      - gradle build --info
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - nimbus-jose-jwt_aws-kms-extension/build/libs/nimbus-jose-jwt_aws-kms-extension-1.0.0.jar