version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mkdir -p ~/opt/gradle
      - wget -q https://services.gradle.org/distributions/gradle-7.1.1-bin.zip -O ~/opt/gradle/gradle-7.1.1-bin.zip
      - yes | unzip ~/opt/gradle/gradle-7.1.1-bin.zip -d ~/opt/gradle
      - export PATH=$HOME/opt/gradle/gradle-7.1.1/bin:$PATH
      - gradle -v
  build:
    commands:
      - echo "Build started on `date`"
      - gradle build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/nimbus-jose-jwt_aws-kms-extension-1.0.0.jar